export const CREATE_TODO = 'CREATE_TODO';

export const CREATE_TASK = 'CREATE_TASK';

export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';

export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const CHECK_TASK = 'CHECK_TASK';

export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const CLEAR_FILTER = 'CLEAR_FILTER';

export const FETCHING_TASK = 'FETCHING_TASK';

export const FETCHING_TASK_SUCCESS = 'FETCHING_TASK_SUCCESS';

export const FETCHING_TASK_FAILURE = 'FETCHING_TASK_FAILURE';
